### ISSUE TITLE
SOS!Help!!!   execute "catkin build lamp" failed

### ISSUE THREAD

**Issue by YigaoWang** [NeBula-Autonomy/LAMP#10]

**Comment by YigaoWang** [comment]
![image](https://user-images.githubusercontent.com/62236109/201076002-a56823c4-6df7-4007-8962-7f5714ac6e49.png)
Follow the steps of gitlab to install completely, but encounter a bug. Do you know the reason?

**Comment by yunzc** [comment]
What version of PCL do you have? Seems like the issue is with [PCL_DEPRECATED](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/pcl_macros.h#L156).

**Comment by YigaoWang** [comment]
> What version of PCL do you have? Seems like the issue is with [PCL_DEPRECATED](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/pcl_macros.h#L156).

ThankYou very much,I'll have a try!

**Comment by YigaoWang** [comment]
Should I install PCL from this website https://github.com/PointCloudLibrary/pcl
![image](https://user-images.githubusercontent.com/62236109/201298469-cade9931-9ee5-4322-af96-63525a088dd2.png)

**Comment by yunzc** [comment]
What version do you currently have? Have you already done `sudo apt-get install ros-melodic-pcl-ros`?

**Comment by YigaoWang** [comment]
> What version do you currently have? Have you already done `sudo apt-get install ros-melodic-pcl-ros`?

![image](https://user-images.githubusercontent.com/62236109/201355890-983fc01d-029f-485a-b05a-31f337c05f0a.png)
My Linux OS is Ubuntu20.04，so I install the ROS noetic, then I execute the command `sudo apt-get install ros-noetic-pcl-ros`, the result is show in the picture. What should I do in the next step?Thanks!!!

**Comment by yunzc** [comment]
What is your output if you run `ldconfig -p | grep pcl`?

**Comment by YigaoWang** [comment]
> What is your output if you run `ldconfig -p | grep pcl`?

![image](https://user-images.githubusercontent.com/62236109/201358282-7999a40c-4900-4b9f-b4a3-fece759d500f.png)
Output is show in this picture😀

**Comment by yunzc** [comment]
Ahh I see why now. I have 1.8 and you have 1.10, and the PCL_DEPRECATED macro is removed in 1.10. 
As seen here [1.8](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.8.0/common/include/pcl/pcl_macros.h) and [1.10](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.10.0/common/include/pcl/pcl_macros.h)
I think switching to PCL 1.8 is your best bet.

**Comment by YigaoWang** [comment]
> Ahh I see why now. I have 1.8 and you have 1.10, and the PCL_DEPRECATED macro is removed in 1.10. As seen here [1.8](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.8.0/common/include/pcl/pcl_macros.h) and [1.10](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.10.0/common/include/pcl/pcl_macros.h) I think switching to PCL 1.8 is your best bet.

It's my honor to get a timely reply from the technical leader👍👍👍. I'll study it later🤭🤭🤭.

**Comment by YigaoWang** [comment]
> Ahh I see why now. I have 1.8 and you have 1.10, and the PCL_DEPRECATED macro is removed in 1.10. As seen here [1.8](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.8.0/common/include/pcl/pcl_macros.h) and [1.10](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.10.0/common/include/pcl/pcl_macros.h) I think switching to PCL 1.8 is your best bet.
![image](https://user-images.githubusercontent.com/62236109/201522468-f1a03a8f-a830-4f74-9b7d-dbf25f70c35e.png)

Sorry, I compiled pcl1.8 and then executed ldconfig - p | grep pcl, but the result is still the same as the previous picture, showing pcl 1.10. What should I do next?

**Comment by yunzc** [comment]
Did you install from source?
