### ISSUE TITLE
implement without loop closure

### ISSUE THREAD

**Issue by BamsaAhmed** [NeBula-Autonomy/LAMP#12]
Hi
Can i execute the code without loop closure?

**Comment by yunzc** [comment]
Hi
Yes, you can just remove the loop closure modules from the launch file https://github.com/NeBula-Autonomy/LAMP/blob/main/lamp/launch/turn_on_lamp_base.launch#L104-L105

**Comment by octopuscabbage** [comment]
you could also add a parameter in that launch file if you'd like to do it programmatically

**Comment by BamsaAhmed** [comment]
@yunzc 
thank you for your response, I have another question it is about the dataset , is it provides maps to the algorithm directly?

**Comment by yunzc** [comment]
@BamsaAhmed apologies, missed this message. Is your question resolved?
