### ISSUE TITLE
SOS ！！！Running Error

### ISSUE THREAD

**Issue by leng-96** [NeBula-Autonomy/LAMP#13]
When I run  roslaunch lamp turn_on_lamp_base.launch robot_namespace:=base1

![2023-04-14 00-26-50 的屏幕截图](https://user-images.githubusercontent.com/106567418/231825047-29c4de44-c8ba-4561-81d0-e948bcc44a41.png)

Who can help me？ Thinks

**Comment by yunzc** [comment]
A little difficult to tell what is going on here. Could you try running with GDB and provide the backtrace of the error?
