### ISSUE TITLE
Error in building kimera_rpgo

### ISSUE THREAD

**Issue by ajxdhe** [NeBula-Autonomy/LAMP#14]
When I builded kimera_rpgo ,I encountered a issue

In file included from /home/skywalker/lamp_ws/src/kimera_rpgo/include/KimeraRPGO/RobustSolver.h:17,
                 from /home/skywalker/lamp_ws/src/kimera_rpgo/src/RobustSolver.cpp:6:

usr/local/include/gtsam/nonlinear/GncOptimizer.h:69:39: **error: no matching function for call to** ‘dynamic_pointer_cast<gtsam::NoiseModelFactor>(const sharedFactor)’   NoiseModelFactor>(graph[i]);

maybe I installed the wrong version of gtsam(4.0.3).which version can match kimera_rpgo?

Best

**Comment by yunzc** [comment]
Hi. The latest version I have tested it was 4.2a7. Can you check if this version works for you?
