### ISSUE TITLE
No module named torch_geometric.nn

### ISSUE THREAD

**Issue by Lu-tju** [NeBula-Autonomy/LAMP#2]
Hi, I have read you paper LAMP2.0, which inspire me a lot. 
However, I meet some problems when running your package with `roslaunch lamp turn_on_lamp_base.launch robot_namespace:=base1`.
```
Traceback (most recent call last):
  File "/home/lamp_ws/src/localizer_lamp/loop_closure/src/loop_closure_batcher_node.py", line 8, in <module>
    from loop_closure_batcher import LoopClosureBatcher
  File "/home/lamp_ws/src/localizer_lamp/loop_closure/src/loop_closure_batcher.py", line 1, in <module>
    from gnn.gnn_model import LoopClosureGNN
  File "/home/lamp_ws/src/localizer_lamp/loop_closure/src/gnn/gnn_model.py", line 8, in <module>
    from torch_geometric.nn import GCNConv, GraphConv, GATConv, SAGEConv, GMMConv, NNConv
ImportError: No module named torch_geometric.nn
```
The environment is consistent with your instructions
```
Ubuntu 18.04 
CUDA 10.2
Python 3.7
torch==1.4.0
torch-scatter==1.4.0
torch-sparse==0.4.4
torch-cluster==1.4.5
torch-spline-conv==1.1.1
torch-geometric==1.3.2
```
![Screenshot from 2022-06-28 19-07-45](https://user-images.githubusercontent.com/57125479/176165872-c47c7630-295b-484c-bd83-92a2da2135a2.png)

I would be very grateful if you could open a docker.

**Comment by octopuscabbage** [comment]
Hi, the loop closure batcher (called the graph information prioritization in the paper) runs in python 2, you can see this line here

[#!/usr/bin/env python2](https://github.com/NeBula-Autonomy/LAMP/blob/f68668ab2a7487f284854d0e2bc666d2170381c0/loop_closure/src/loop_closure_batcher_node.py#L1)

I believe you have installed the requirements into your global python3 requirements.

To fix this you should install the requirements into your python2 installation using ```python2 -m pip install -r requirements.txt` ``
and installing the requirements

**Comment by octopuscabbage** [comment]
Addressed here: https://github.com/NeBula-Autonomy/LAMP/pull/3
