### ISSUE TITLE
i can't make the teaser++. I need help very much!!!!

### ISSUE THREAD

**Issue by junxiaofanchen** [NeBula-Autonomy/LAMP#20]
Have you ever been in this situation when you make the teaser++ feature/pcl-macher (（/usr/bin/ld： CMakeFiles/all_tests.dir/evaluation-test.cc.o： in function teaser：：SolutionEvaluator：：SolutionEvaluator（Eigen：：Matrix<double， 3， -1， 0， 3， -1> const&， Eigen：：Matrix<double， 3， -1， 0， 3， -1> const&， double）' /usr/bin
/ld： evaluation-test.cc:（.text+0x371）： 未定义引用“teaser：：SolutionEvaluator：：computeErrorMetric（Eigen：：Matrix<double， 3， 3， 0， 3， 3> const&， Eigen：：Matrix<double， 3， 1， 0， 3， 1> const&）'）)

I need help very much！！！

**Comment by yunzc** [comment]
Duplicated from https://github.com/MIT-SPARK/TEASER-plusplus/issues/174

**Comment by junxiaofanchen** [comment]
Now I've solved this issue because I compiled teaser++ separately and forgot to use -DBUILD_TEASER_FPFH=ON.
for Author's readme.md “Build this package in a catkin workspace ” part，you need add ’catkin build teaserpp‘ before catkin build lamp.because lamp use c++14,but teaserpp use c++11.If use build lamp to build teaserpp,it will error.
