### ISSUE TITLE
Covariance Ordering

### ISSUE THREAD

**Issue by DanMcGann** [NeBula-Autonomy/LAMP#21]
# Covariance Ordering in Lamp
Here the ordering for covariances is documented as $[T_x, T_y, T_z, R_x, R_y, R_z]$

https://github.com/NeBula-Autonomy/LAMP/blob/6caea1b69f95b3288c6cdb2279cc96ac2f461bd3/pose_graph_msgs/msg/PoseGraphEdge.msg#L21

# Covariance Ordering in GTSAM
For all relevant GTSAM factors (Priors and Between) used in LAMP backend, the error vector is exists in the tangent space of the Lie Group (SE(3) in this context). Therefore, the covariance for such factors must match the order of this tangent space. 

GTSAM uses a SE(3) Tangent space ordering of $[R_x, R_y, R_z, T_x, T_y, T_z, ]$ which is documented here: 
```
  /// Exponential map at identity - create a rotation from canonical coordinates \f$ [R_x,R_y,R_z,T_x,T_y,T_z] \f$
  static Pose3 Expmap(const Vector6& xi, OptionalJacobian<6, 6> Hxi = {});

  /// Log map at identity - return the canonical coordinates \f$ [R_x,R_y,R_z,T_x,T_y,T_z] \f$ of this rotation
  static Vector6 Logmap(const Pose3& pose, OptionalJacobian<6, 6> Hpose = {});
  ```
  https://github.com/borglab/gtsam/blob/9d70605d488968eb766874d210b3f734149f3b66/gtsam/geometry/Pose3.h#L138-L142

# Conversions Between Standards
From the above documentation it is clear that LAMP and GTSAM use different conventions for covariance ordering. Therefore, I would expect LAMP to preform a block re-order of covariances when converting between messages and GTSAM noise models.

However, no such reordering is preformed?
https://github.com/NeBula-Autonomy/LAMP/blob/6caea1b69f95b3288c6cdb2279cc96ac2f461bd3/lamp_utils/include/lamp_utils/CommonFunctions.h#L60-L72

# Questions
The above inconsistencies leave the user with a number of questions. Is there a bug in the LAMP code (i.e. the covariances SHOULD be reordered but are not being re-ordered)? Or is the documentation out-of date?

Maybe more concretely I should ask:
* What is the convention for covariance order in LAMP PoseGraph Messages?
* What is the convention for covariance order in LAMP G2O Files (supplied in the example datasets)?

**Comment by yunzc** [comment]
Feel free to ignore the comment in the pose graph msgs, I don't think that was addressing the covariances. Apologies for not cleaning that up. In general it should be rotation first as GTSAM does it.
This is also true for the g2o files.

An example here: https://github.com/NeBula-Autonomy/LAMP/blob/main/loop_closure/src/IcpLoopComputation.cc#L621-L624
