### ISSUE TITLE
Recreating Paper Results

### ISSUE THREAD

**Issue by DanMcGann** [NeBula-Autonomy/LAMP#22]
Hello I am struggling to recreate the results presented in the LAMP 2.0 Paper (https://arxiv.org/pdf/2205.13135.pdf)

# Setup
OS: Ubuntu 20.04
ROS Distro: Noetic
Python: 3.8
Torch: 1.7.1 (With torch-geometric to match)
Cuda: 10.2
GTSAM: 4.2a9 (the hash mentioned in the README did not work)

Note: The above config required only a single change to the repo -- changing `python2` -> `python3` in the `loop_closure_batcher_node.py`, and commenting out the line `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"`

# Experiment Execution
Data: Tunnel Data from https://drive.google.com/drive/folders/1gcUEDBp_aeGwS059xnK4Xv8qlU3JQUNE

Startup Commands
Terminal 1: `roslaunch lamp turn_on_lamp_base.launch robot_namespace:=base1`
Terminal 2: `rosbag play tunnel/rosbag/*.bag -r1 --clock clock:=/clock --wait-for-subscribers`
Terminal 3: `rviz -d $(rospack find lamp)/rviz/lamp_base.rviz`

## Issue 1: Loop Closure Module Bug
At about the 4000 second mark in the tunnel dataset, the loop-closure module starts repeatedly spitting out the following error and seems to fail to produce any more loop-closures.
```
[ERROR] [1702584377.795999]: Error in Run: Traceback (most recent call last):
  File "/home/daniel/Development/lamp_ws/src/localizer_lamp/loop_closure/src/subset_algorithms/base.py", line 54, in run
    self.step()
  File "/home/daniel/Development/lamp_ws/src/localizer_lamp/loop_closure/src/subset_algorithms/gnn.py", line 220, in step
    self.find_initial_solution()
  File "/home/daniel/Development/lamp_ws/src/localizer_lamp/loop_closure/src/subset_algorithms/gnn.py", line 188, in find_i
nitial_solution
    from_node = keys_to_nodes[edge.key_from]
KeyError: 7133701809754866227 
```

## Issue 2: Inlier Loop-Closures
Regardless of the above bug, the loop-closure module does not achieve expected performance.
The paper reports (Table III) that for the tunnel dataset there are 5656 verified loop-closures and 1645 inlier loop-closures.
However, when running LAMP reports that there are only ~350 verified loop-closures and ~170 inlier loop closures. 
While the above bug is affecting this number, because the bug does not affect results until near the end of the dataset, it appears that something else is causing an issue. 

## Issue 3: Trajectory Results
This is likely an affect of the above two issues, but the resulting solution trajectory is very poor relative to the results reported in the paper. Below are two examples map mis-alignments that are are not there in the presented results (Figure: 4)
![image](https://github.com/NeBula-Autonomy/LAMP/assets/24306150/ec90a7f4-4191-482c-9101-ced112609d50)
![image](https://github.com/NeBula-Autonomy/LAMP/assets/24306150/fb332d17-3267-4300-b88e-f0e0dcadb62b)

# Questions
The above results leave me with a few questions
1. Is the loop-closure bug a known issue? are there workarounds to avoid the errors + crashes?
2. Are the default hyper-parameters in the repo the same used to generate the paper results? If not what parameters should be used to re-create the paper performance?

**Comment by yunzc** [comment]
1. Not a known issue. Have not seen it before, but the paper experiments were done with Melodic + python2 with an earlier version, so might have been introduced with new changes. I haven't had the chance to check performance with Noetic yet myself, but can try when I get some spare cycles and get back to you on it.
2. The number of loop closures detected is highly sensitive to compute. However, the bug might also effect things: i.e. if the loop closure prioritization is not working correctly, the significant loop closures might not be detected before crashing (https://arxiv.org/pdf/2205.12402.pdf). Let me find my old experiment files and follow up.

**Comment by DanMcGann** [comment]
Thank you so much for the fast reply!

Given your comments I preformed 2 additional experiments.

1. To account for the affect that compute can have on the number of loop-closures I used the setup-above and replayed the bag with a rate of 0.25 to give the loop-closure module additional time between scans (effectively gave it more compute).

2. To account for the different python+ros versions I setup a docker container with the correct environment and again ran the experiment on the tunnels data set with a replay rate of 0.5.

In both the experiments the lamp code reports ~350 Loop closures detected and ~170 inliers (i.e. the same values as originally reported). While they did deviate some, it was not significant. Additionally, both experiments maintained the trajectory errors shown above.

This would indicate that compute/versioning is not the root cause of the discrepancy between results with the current LAMP code and the results published. I don't have much to go on, but my strong hunch would be it is some difference in configuration parameters. From watching the output the LAMP code as is currently on this repo rejects LOTS of loop closures due to a ICP fitness threshold (default = 0.9), but of course it could be some other parameter that is not as evident from the output.


For reference I have included the docker file I used for the second experiment below.
<details open>
  <summary>Dockerfile</summary>
  
``` 
FROM ros:melodic-robot

# Source ROS
RUN ["/bin/bash", "-c", "source /opt/ros/melodic/setup.bash"]

# Workspace environment
ENV ROS_WS /home/lamp_ws
RUN mkdir -p $ROS_WS/src
WORKDIR $ROS_WS

# APT pre-reqs
RUN apt-get update
RUN apt-get install -y \
    ros-melodic-catkin \
    python-catkin-tools \
    python-pip \
    ros-melodic-pcl-ros \
    libyaml-cpp-dev \
    libtbb-dev \
    ros-melodic-interactive-markers

# PIP pre-reqs
RUN python -m pip install --upgrade pip future setuptools ez_setup wheel 
# Need to Explicitly install torch before torch-geometric packages as their setup imports torch
RUN pip install torch>=1.4.0     
RUN pip install --no-cache-dir \
    torch-scatter==1.4.0 \
    torch-sparse==0.4.4 \
    torch-cluster==1.4.5 \
    torch-spline-conv==1.1.1 \
    torch-geometric==1.3.2 \
    torchvision==0.5.0
# Torch vision version ref: https://pytorch.org/get-started/previous-versions/#v140

# Initialize the workspace
RUN catkin init
RUN catkin config --extend /opt/ros/melodic -DCMAKE_BUILD_TYPE=Release -DGTSAM_TANGENT_PREINTEGRATION=OFF -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DOPENGV_BUILD_WITH_MARCH_NATIVE=OFF -DBUILD_TEASER_FPFH=ON 

# Get the LAMP Code 
WORKDIR $ROS_WS/src
RUN git clone https://github.com/NeBula-Autonomy/LAMP.git localizer_lamp
RUN git clone https://github.com/NeBula-Autonomy/common_nebula_slam.git

# Run wstool for the LAMP dependencies
RUN wstool init
RUN wstool merge localizer_lamp/install/lamp_http.rosinstall
RUN wstool up

# Checkout GTSAM version
WORKDIR $ROS_WS/src/gtsam
# The version specified in the readme does not work due to this bug
# https://github.com/borglab/gtsam/issues/1092
# We need to use a version that contains this commit to avoid bugs: af1dedb879778277dc9fd0759b3defd554d4c947
RUN git checkout 4.2a7

# Checkout Kimera RPGO version
WORKDIR $ROS_WS/src/kimera_rpgo
RUN git checkout master

# Build the LAMP workspace
WORKDIR $ROS_WS
RUN catkin build lamp

# Dataset Directory
ENV DATA_DIR /home/lamp_datasets
RUN mkdir -p $DATA_DIR
WORKDIR $DATA_DIR

# Download the datasets
RUN pip install gdown
# Download the tunnel dataset to /home/lamp_datasets/tunnel
RUN gdown --folder https://drive.google.com/drive/folders/1gcUEDBp_aeGwS059xnK4Xv8qlU3JQUNE 
```
</details>

**Comment by yunzc** [comment]
Thanks for looking into this. 
I found and copied the parameters from our old tunnel experiment configs, adapted it to the current version, and tested it on the dataset and was able to get similar performance. Diff [here ](https://drive.google.com/file/d/1yHvLsJ8ddNVGnA1PZ_S7Kt3YuK_lvopr/view?usp=sharing). Hope this helps!

![Screenshot from 2023-12-26 04-30-18](https://github.com/NeBula-Autonomy/LAMP/assets/18037712/f68402b2-daa1-4341-9cb3-dc5a20e3d851)

![Screenshot from 2023-12-26 04-30-44](https://github.com/NeBula-Autonomy/LAMP/assets/18037712/51cd5992-3b15-4f72-a898-869e87f05440)
