### ISSUE TITLE
Could not find a package configuration file provided by "core_msgs"?

### ISSUE THREAD

**Issue by yuan0524** [NeBula-Autonomy/LAMP#8]
When I run catkin build lamp, an error is displayed.
Could not find a package configuration file provided by "core_msgs" with
  any of the following names:
    core_msgsConfig.cmake
    core_msgs-config.cmake

  Add the installation prefix of "core_msgs" to CMAKE_PREFIX_PATH or set
  "core_msgs_DIR" to a directory containing one of the above files.  If
  "core_msgs" provides a separate development package or SDK, be sure it has
  been installed.
However, I was unable to locate the software package using sudo apt install ros-melodic-core_msgs.

**Comment by yunzc** [comment]
Sorry I did not see that you reopened this issue. I was using Ubuntu 18.04 and ROS melodic. The torch instructions here should be for python2. Personally my setup was with a python virtualenv.
